# Generated by Django 3.1.2 on 2020-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile-pictures/user.png', upload_to='profile-pictures'),
        ),
    ]
