# Generated by Django 3.1.2 on 2020-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201029_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to='profile-pictures'),
        ),
    ]
