# Generated by Django 3.1.2 on 2020-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201029_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user.svg', upload_to='profile-pictures'),
        ),
    ]
